# Generated by Django 5.1.2 on 2024-11-02 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nome_prod', models.CharField(max_length=150, unique=True)),
                ('vlr_prod', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('qntd_prod', models.IntegerField(default=0)),
                ('entrada_prod', models.DateField()),
                ('saida_prod', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
