# Generated by Django 5.1.2 on 2024-11-02 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatoriosVisitas',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=150)),
                ('nom_tecnico', models.CharField(max_length=150)),
                ('nom_tecnico_f', models.CharField(max_length=150)),
                ('nom_cliente', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=250)),
                ('data', models.DateField(blank=True)),
                ('prod_usado', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
